// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Geo-restriction Option Group

package ytdlp

// Use this proxy to verify the IP address for some geo-restricted sites. The
// default proxy specified by --proxy (or none, if the option is not present) is
// used for the actual downloading
//
// GeoVerificationProxy maps to cli flags: --geo-verification-proxy=URL.
func (c *Command) GeoVerificationProxy(url string) *Command {
	c.addFlag(&Flag{
		ID:   "geo_verification_proxy",
		Flag: "--geo-verification-proxy",
		Args: []string{url},
	})
	return c
}

// CnVerificationProxy maps to cli flags: --cn-verification-proxy=URL.
func (c *Command) CnVerificationProxy(url string) *Command {
	c.addFlag(&Flag{
		ID:   "cn_verification_proxy",
		Flag: "--cn-verification-proxy",
		Args: []string{url},
	})
	return c
}

// How to fake X-Forwarded-For HTTP header to try bypassing geographic restriction.
// One of "default" (only when known to be useful), "never", an IP block in CIDR
// notation, or a two-letter ISO 3166-2 country code
//
// Xff maps to cli flags: --xff=VALUE.
func (c *Command) Xff(value string) *Command {
	c.addFlag(&Flag{
		ID:   "geo_bypass",
		Flag: "--xff",
		Args: []string{value},
	})
	return c
}

// GeoBypassCountry maps to cli flags: --geo-bypass-country=CODE.
func (c *Command) GeoBypassCountry(code string) *Command {
	c.addFlag(&Flag{
		ID:   "geo_bypass",
		Flag: "--geo-bypass-country",
		Args: []string{code},
	})
	return c
}

// GeoBypassIpBlock maps to cli flags: --geo-bypass-ip-block=IP_BLOCK.
func (c *Command) GeoBypassIpBlock(ipBlock string) *Command {
	c.addFlag(&Flag{
		ID:   "geo_bypass",
		Flag: "--geo-bypass-ip-block",
		Args: []string{ipBlock},
	})
	return c
}
