// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Network Option Group

package ytdlp

import (
	"strconv"
)

// Use the specified HTTP/HTTPS/SOCKS proxy. To enable SOCKS proxy, specify a
// proper scheme, e.g. socks5://user:pass@127.0.0.1:1080/. Pass in an empty string
// (--proxy "") for direct connection
//
//   - See [Command.UnsetProxy], for unsetting the flag.
//   - Proxy maps to cli flags: --proxy=URL.
func (c *Command) Proxy(url string) *Command {
	c.addFlag(&Flag{
		ID:   "proxy",
		Flag: "--proxy",
		Args: []string{url},
	})
	return c
}

// UnsetProxy unsets any flags that were previously set by
// [Proxy].
func (c *Command) UnsetProxy() *Command {
	c.removeFlagByID("proxy")
	return c
}

// Time to wait before giving up, in seconds
//
//   - See [Command.UnsetSocketTimeout], for unsetting the flag.
//   - SocketTimeout maps to cli flags: --socket-timeout=SECONDS.
func (c *Command) SocketTimeout(seconds float64) *Command {
	c.addFlag(&Flag{
		ID:   "socket_timeout",
		Flag: "--socket-timeout",
		Args: []string{
			strconv.FormatFloat(seconds, 'g', -1, 64),
		},
	})
	return c
}

// UnsetSocketTimeout unsets any flags that were previously set by
// [SocketTimeout].
func (c *Command) UnsetSocketTimeout() *Command {
	c.removeFlagByID("socket_timeout")
	return c
}

// Client-side IP address to bind to
//
//   - See [Command.UnsetSourceAddress], for unsetting the flag.
//   - SourceAddress maps to cli flags: --source-address=IP.
func (c *Command) SourceAddress(ip string) *Command {
	c.addFlag(&Flag{
		ID:   "source_address",
		Flag: "--source-address",
		Args: []string{ip},
	})
	return c
}

// UnsetSourceAddress unsets any flags that were previously set by
// [SourceAddress].
func (c *Command) UnsetSourceAddress() *Command {
	c.removeFlagByID("source_address")
	return c
}

// Make all connections via IPv4
//
//   - See [Command.UnsetForceIpv4], for unsetting the flag.
//   - ForceIpv4 maps to cli flags: -4/--force-ipv4.
func (c *Command) ForceIpv4() *Command {
	c.addFlag(&Flag{
		ID:   "source_address",
		Flag: "--force-ipv4",
		Args: nil,
	})
	return c
}

// UnsetForceIpv4 unsets any flags that were previously set by
// [ForceIpv4].
func (c *Command) UnsetForceIpv4() *Command {
	c.removeFlagByID("source_address")
	return c
}

// Make all connections via IPv6
//
//   - See [Command.UnsetForceIpv6], for unsetting the flag.
//   - ForceIpv6 maps to cli flags: -6/--force-ipv6.
func (c *Command) ForceIpv6() *Command {
	c.addFlag(&Flag{
		ID:   "source_address",
		Flag: "--force-ipv6",
		Args: nil,
	})
	return c
}

// UnsetForceIpv6 unsets any flags that were previously set by
// [ForceIpv6].
func (c *Command) UnsetForceIpv6() *Command {
	c.removeFlagByID("source_address")
	return c
}

// Enable file:// URLs. This is disabled by default for security reasons.
//
//   - See [Command.UnsetEnableFileUrls], for unsetting the flag.
//   - EnableFileUrls maps to cli flags: --enable-file-urls.
func (c *Command) EnableFileUrls() *Command {
	c.addFlag(&Flag{
		ID:   "enable_file_urls",
		Flag: "--enable-file-urls",
		Args: nil,
	})
	return c
}

// UnsetEnableFileUrls unsets any flags that were previously set by
// [EnableFileUrls].
func (c *Command) UnsetEnableFileUrls() *Command {
	c.removeFlagByID("enable_file_urls")
	return c
}
