// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Thumbnail Option Group

package ytdlp

// Write thumbnail image to disk
//
//   - See [Command.UnsetWriteThumbnail], for unsetting the flag.
//   - WriteThumbnail maps to cli flags: --write-thumbnail.
func (c *Command) WriteThumbnail(value string) *Command {
	c.addFlag(&Flag{
		ID:   "writethumbnail",
		Flag: "--write-thumbnail",
		Args: []string{value},
	})
	return c
}

// UnsetWriteThumbnail unsets any flags that were previously set by
// [Command.WriteThumbnail].
func (c *Command) UnsetWriteThumbnail() *Command {
	c.removeFlagByID("writethumbnail")
	return c
}

// Do not write thumbnail image to disk (default)
//
//   - See [Command.UnsetWriteThumbnail], for unsetting the flag.
//   - NoWriteThumbnail maps to cli flags: --no-write-thumbnail.
func (c *Command) NoWriteThumbnail() *Command {
	c.addFlag(&Flag{
		ID:   "writethumbnail",
		Flag: "--no-write-thumbnail",
		Args: nil,
	})
	return c
}

// Write all thumbnail image formats to disk
//
//   - See [Command.UnsetWriteAllThumbnails], for unsetting the flag.
//   - WriteAllThumbnails maps to cli flags: --write-all-thumbnails.
func (c *Command) WriteAllThumbnails() *Command {
	c.addFlag(&Flag{
		ID:   "writethumbnail",
		Flag: "--write-all-thumbnails",
		Args: nil,
	})
	return c
}

// UnsetWriteAllThumbnails unsets any flags that were previously set by
// [Command.WriteAllThumbnails].
func (c *Command) UnsetWriteAllThumbnails() *Command {
	c.removeFlagByID("writethumbnail")
	return c
}

// List available thumbnails of each video. Simulate unless --no-simulate is used
//
//   - See [Command.UnsetListThumbnails], for unsetting the flag.
//   - ListThumbnails maps to cli flags: --list-thumbnails.
func (c *Command) ListThumbnails() *Command {
	c.addFlag(&Flag{
		ID:   "list_thumbnails",
		Flag: "--list-thumbnails",
		Args: nil,
	})
	return c
}

// UnsetListThumbnails unsets any flags that were previously set by
// [Command.ListThumbnails].
func (c *Command) UnsetListThumbnails() *Command {
	c.removeFlagByID("list_thumbnails")
	return c
}
