// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Thumbnail Option Group

package ytdlp

// Write thumbnail image to disk
//
// WriteThumbnail maps to cli flags: --write-thumbnail.
func (c *Command) WriteThumbnail(value string) *Command {
	c.addFlag(&Flag{
		ID:   "writethumbnail",
		Flag: "--write-thumbnail",
		Args: []string{value},
	})
	return c
}

// Do not write thumbnail image to disk (default)
//
// NoWriteThumbnail maps to cli flags: --no-write-thumbnail.
func (c *Command) NoWriteThumbnail() *Command {
	c.addFlag(&Flag{
		ID:   "writethumbnail",
		Flag: "--no-write-thumbnail",
		Args: nil,
	})
	return c
}
