// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// Code generated by cmd/codegen. DO NOT EDIT.
//
// Video Format Option Group

package ytdlp

type VideoFormatBuilder struct {
	parent *Command
}

// Then jumps back to the base command builder, if you want to add additional flags
// from another flag builder.
func (ff *VideoFormatBuilder) Then() *Command {
	return ff.parent
}

// Video format code, see "FORMAT SELECTION" for more details
//
// Format maps to cli flags: -f/--format=FORMAT.
func (ff *VideoFormatBuilder) Format(format string) *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "format",
		Flag: "--format",
		Args: []string{format},
	})
	return ff
}

// Force user specified sort order to have precedence over all fields, see "Sorting
// Formats" for more details (Alias: --S-force)
//
// FormatSortForce maps to cli flags: --format-sort-force/--S-force=FORMAT.
func (ff *VideoFormatBuilder) FormatSortForce() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "format_sort_force",
		Flag: "--format-sort-force",
		Args: nil,
	})
	return ff
}

// Some fields have precedence over the user specified sort order (default)
//
// NoFormatSortForce maps to cli flags: --no-format-sort-force=FORMAT.
func (ff *VideoFormatBuilder) NoFormatSortForce() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "format_sort_force",
		Flag: "--no-format-sort-force",
		Args: nil,
	})
	return ff
}

// Allow multiple video streams to be merged into a single file
//
// VideoMultistreams maps to cli flags: --video-multistreams.
func (ff *VideoFormatBuilder) VideoMultistreams() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_multiple_video_streams",
		Flag: "--video-multistreams",
		Args: nil,
	})
	return ff
}

// Only one video stream is downloaded for each output file (default)
//
// NoVideoMultistreams maps to cli flags: --no-video-multistreams.
func (ff *VideoFormatBuilder) NoVideoMultistreams() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_multiple_video_streams",
		Flag: "--no-video-multistreams",
		Args: nil,
	})
	return ff
}

// Allow multiple audio streams to be merged into a single file
//
// AudioMultistreams maps to cli flags: --audio-multistreams.
func (ff *VideoFormatBuilder) AudioMultistreams() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_multiple_audio_streams",
		Flag: "--audio-multistreams",
		Args: nil,
	})
	return ff
}

// Only one audio stream is downloaded for each output file (default)
//
// NoAudioMultistreams maps to cli flags: --no-audio-multistreams.
func (ff *VideoFormatBuilder) NoAudioMultistreams() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_multiple_audio_streams",
		Flag: "--no-audio-multistreams",
		Args: nil,
	})
	return ff
}

// Prefer video formats with free containers over non-free ones of same quality.
// Use with "-S ext" to strictly prefer free containers irrespective of quality
//
// PreferFreeFormats maps to cli flags: --prefer-free-formats.
func (ff *VideoFormatBuilder) PreferFreeFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "prefer_free_formats",
		Flag: "--prefer-free-formats",
		Args: nil,
	})
	return ff
}

// Don't give any special preference to free containers (default)
//
// NoPreferFreeFormats maps to cli flags: --no-prefer-free-formats.
func (ff *VideoFormatBuilder) NoPreferFreeFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "prefer_free_formats",
		Flag: "--no-prefer-free-formats",
		Args: nil,
	})
	return ff
}

// Check all formats for whether they are actually downloadable
//
// CheckAllFormats maps to cli flags: --check-all-formats.
func (ff *VideoFormatBuilder) CheckAllFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "check_formats",
		Flag: "--check-all-formats",
		Args: nil,
	})
	return ff
}

// Do not check that the formats are actually downloadable
//
// NoCheckFormats maps to cli flags: --no-check-formats.
func (ff *VideoFormatBuilder) NoCheckFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "check_formats",
		Flag: "--no-check-formats",
		Args: nil,
	})
	return ff
}

// List available formats of each video. Simulate unless --no-simulate is used
//
// ListFormats maps to cli flags: -F/--list-formats.
func (ff *VideoFormatBuilder) ListFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "listformats",
		Flag: "--list-formats",
		Args: nil,
	})
	return ff
}

// ListFormatsAsTable sets the "list-formats-as-table" flag to "true".
//
// ListFormatsAsTable maps to cli flags: --list-formats-as-table.
func (ff *VideoFormatBuilder) ListFormatsAsTable() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "listformats_table",
		Flag: "--list-formats-as-table",
		Args: nil,
	})
	return ff
}

// ListFormatsOld sets the "list-formats-old" flag to "false".
//
// ListFormatsOld maps to cli flags: --list-formats-old/--no-list-formats-as-table.
func (ff *VideoFormatBuilder) ListFormatsOld() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "listformats_table",
		Flag: "--list-formats-old",
		Args: nil,
	})
	return ff
}

// Containers that may be used when merging formats, separated by "/", e.g.
// "mp4/mkv". Ignored if no merge is required. (currently supported: avi, flv, mkv,
// mov, mp4, webm)
//
// MergeOutputFormat maps to cli flags: --merge-output-format=FORMAT.
func (ff *VideoFormatBuilder) MergeOutputFormat(format string) *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "merge_output_format",
		Flag: "--merge-output-format",
		Args: []string{format},
	})
	return ff
}

// AllowUnplayableFormats sets the "allow-unplayable-formats" flag to "true".
//
// AllowUnplayableFormats maps to cli flags: --allow-unplayable-formats.
func (ff *VideoFormatBuilder) AllowUnplayableFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_unplayable_formats",
		Flag: "--allow-unplayable-formats",
		Args: nil,
	})
	return ff
}

// NoAllowUnplayableFormats sets the "no-allow-unplayable-formats" flag to "false".
//
// NoAllowUnplayableFormats maps to cli flags: --no-allow-unplayable-formats.
func (ff *VideoFormatBuilder) NoAllowUnplayableFormats() *VideoFormatBuilder {
	ff.parent.addFlag(&Flag{
		ID:   "allow_unplayable_formats",
		Flag: "--no-allow-unplayable-formats",
		Args: nil,
	})
	return ff
}
