name: test

on:
  pull_request:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

env:
  YTDLP_DEBUG: true

jobs:
  go-test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    permissions:
      contents: read
    with: { num-minor: 1, num-patch: 2 }
  go-lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
    permissions:
      checks: write
      contents: read
      pull-requests: read
      security-events: write
      statuses: write
    secrets: inherit
